name: Crystal CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "31 2 * * 2"

jobs:
  build:
    runs-on: ubuntu-latest
    name: "crystal: ${{ matrix.crystal }}, stable: ${{ matrix.stable }}"
    continue-on-error: ${{ !matrix.stable }}
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        crystal:
          - 1.1.1
          - 1.4.1
        include:
          - crystal: nightly
            stable: false

    container:
      image: crystallang/crystal:${{ matrix.crystal }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec -Dpreview_mt --order random --error-on-warnings
#    - name: Run build
#      run: shards build -Dpreview_mt
    - name: Run format
      run: crystal tool format --check
